"""Add day model

Revision ID: 030cc33ae852
Revises: 64173c208aae
Create Date: 2018-08-11 23:25:39.610740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030cc33ae852'
down_revision = '64173c208aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=25), nullable=False),
    sa.Column('indoor_avg_temp', sa.Float(), nullable=False),
    sa.Column('indoor_avg_hum', sa.Float(), nullable=False),
    sa.Column('outdoor_avg_temp', sa.Float(), nullable=False),
    sa.Column('outdoor_avg_hum', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days')
    # ### end Alembic commands ###
